---
title: "NBA 2014-2015球季 各隊分析"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##把資料讀進來的程式碼
```{r echo=T}
if (!require('SportsAnalytics')){
  install.packages("SportsAnalytics")
  library(SportsAnalytics)
}
NBA1415<-fetch_NBAPlayerStatistics("14-15")
```

##各隊最辛苦的球員

找出各隊球員中上場總分鐘數最多的一位再由總分鐘數多到少排列

```{r echo=T}
TMPmax<-aggregate(TotalMinutesPlayed~Team,NBA1415,max)
MMP<-merge(NBA1415,TMPmax)
output<-MMP[order(MMP$TotalMinutesPlayed,decreasing = T),c("Team","Name","TotalMinutesPlayed")]
library(knitr)
kable(output, digits=2)
```


##各隊得分王

找出各隊球員中總得分最高的一位再由得分多到少排列

```{r echo=T}
TPmax<-aggregate(TotalPoints~Team,NBA1415,max)
MP<-merge(NBA1415,TPmax)
output<-MP[order(MP$TotalPoints,decreasing = T),c("Team","Name","TotalPoints")]
library(knitr)
kable(output, digits=2)
```

##各隊最有效率的球員

找出各隊員中效率最高(總得分/出戰分鐘數)者，再由數據多到少排列

```{r echo=T}
NBA1415$effcient<- NBA1415$TotalPoints / NBA1415$TotalMinutesPlayed
effcientmax<-aggregate(effcient~Team,NBA1415,max)
Maxeffcient<-merge(NBA1415,effcientmax)
output<-Maxeffcient[order(Maxeffcient$effcient,decreasing = T),c("Team","Name","effcient")]
library(knitr)
kable(output, digits=2)
```

##各隊三分球出手最準的球員

找出各隊球員中三分球命中率最高者(命中次數/出手次數) ，再由數據多到少排列

```{r echo=T}
NBA1415$accuracy<- NBA1415$ThreesMade / NBA1415$ThreesAttempted
accuracymax<-aggregate(accuracy~Team,NBA1415,max)
Maxaccuracy<-merge(NBA1415,accuracymax)
output<-Maxaccuracy[order(Maxaccuracy$accuracy,decreasing = T),c("Team","Name","accuracy")]
library(knitr)
kable(output, digits=2)
```